---
title: "Stochastic Processes"
toc: true
---

This blog willl develop an introductory Graduate Course on Stochastic Processes,with the contents ranging from 
Discrete Time Homogenous Markov Chains with emphasis on Finite State Space.This will be folloed by a treatment of Poisson Processes 
and we will end with an introduction to Martingales and Brownian Motion.

Each Blog will contain some small excercises that may include some small generalisations,prompting to finish some specific steps of a proof
or working out an example.

If you intend to submit a solution kindly type it in the comment box with reference to the excercise number.The first correct and complete solution will be added to the notes 
citing the solution provider.

The principal reference is:

> Richard Durrett, *Essentials of Stochastic Processes*.

Other references may be cited when necessary.

The prerequisites necessary are mainly undergraduate mathematical maturity and a graduate first course in probability theory with some measure theoretic flavour.

If there are any points in the blog which you may feel is erroneous or needs more explanation kindly mention in the comments.


## Lecture index

**Lecture 1.** [Markov Chains And Transition Probabilities](posts/01-markov-chains-lecture-1.qmd)  
